"""Build the static site from src/ into the repository root.

Run from anywhere:  python3 tools/build.py

- src/site.json         contact details, links and navigation (edit this first)
- src/partials/*.html   shared head, header and footer
- src/pages/**.html     one file per page; the first line is a meta comment:
                        <!--meta {"title": "...", "description": "...", "css": ["home"], "js": ["hero"]} -->

src/pages/about.html becomes about/index.html, src/pages/services/websites.html
becomes services/websites/index.html, and index.html / 404.html stay where
they are. Output files are committed so GitHub Pages can serve them as-is.
Tokens such as {{root}}, {{email}} or {{whatsappUrl}} are replaced in every file.
"""
import html
import json
import re
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
META = re.compile(r"^<!--meta (\{.*?\}) -->\n", re.S)


def load_site():
    site = json.loads((SRC / "site.json").read_text())
    site["whatsappUrl"] = f"https://wa.me/{site['whatsapp']}?text={quote(site['whatsappMessage'])}"
    site["mailtoUrl"] = f"mailto:{site['email']}"
    return site


def output_path(page: Path) -> Path:
    rel = page.relative_to(SRC / "pages")
    if rel.name in ("index.html", "404.html") and rel.parent == Path("."):
        return ROOT / rel
    if rel.name == "index.html":
        return ROOT / rel.parent / "index.html"
    return ROOT / rel.with_suffix("") / "index.html"


def nav_links(site, root, section, cls):
    items = []
    for item in site["nav"]:
        current = ' aria-current="page"' if item["section"] == section else ""
        items.append(f'<a class="{cls}" href="{root}{item["href"]}"{current}>{item["label"]}</a>')
    return "\n".join(items)


def render(text, tokens):
    def sub(match):
        key = match.group(1)
        if key not in tokens:
            raise KeyError(f"unknown token {{{{{key}}}}}")
        return str(tokens[key])
    return re.sub(r"\{\{(\w+)\}\}", sub, text)


def build():
    site = load_site()
    partials = {p.stem: p.read_text() for p in (SRC / "partials").glob("*.html")}
    pages = sorted((SRC / "pages").rglob("*.html"))
    urls = []
    for page in pages:
        raw = page.read_text()
        match = META.match(raw)
        if not match:
            raise SystemExit(f"{page}: missing <!--meta {{...}} --> first line")
        meta = json.loads(match.group(1))
        body = raw[match.end():]
        out = output_path(page)
        depth = len(out.relative_to(ROOT).parts) - 1
        is_404 = out.name == "404.html"
        # 404.html is served from any missing URL, so it needs absolute paths.
        root = site["basePath"] if is_404 else "../" * depth
        folder = out.relative_to(ROOT).parent
        canonical = site["siteUrl"] + ("" if folder == Path(".") else folder.as_posix() + "/")
        title = meta["title"]
        tokens = {
            **{k: v for k, v in site.items() if isinstance(v, str)},
            "root": root,
            "title": html.escape(title if title.startswith(site["name"]) else f"{title} · {site['name']}"),
            "description": html.escape(meta["description"]),
            "canonical": canonical,
            "year": "2026",
            "pageClass": meta.get("bodyClass", ""),
            "navDesktop": nav_links(site, root, meta.get("section"), "nav-link"),
            "navMobile": nav_links(site, root, meta.get("section"), "menu-link"),
            "extraCss": "".join(f'<link rel="stylesheet" href="{root}assets/css/{c}.css">\n' for c in meta.get("css", [])),
            "extraJs": "".join(f'<script src="{root}assets/js/{j}.js" defer></script>\n' for j in meta.get("js", [])),
            "noindex": '<meta name="robots" content="noindex">\n' if meta.get("noindex") else "",
        }
        # Partials may use tokens and other partials ({{partial_lockup}}); pages may use both.
        # Two passes resolve one level of nesting; {{content}} is filled in last.
        tokens["content"] = "{{content}}"
        tokens.update({f"partial_{k}": v for k, v in partials.items()})
        for _ in range(2):
            tokens.update({f"partial_{k}": render(v, tokens) for k, v in partials.items()})
        result = render(tokens["partial_layout"], {**tokens, "content": render(body, tokens)})
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(result)
        if not is_404 and not meta.get("noindex"):
            urls.append(canonical)
        print("built", out.relative_to(ROOT))

    config = {k: site[k] for k in ("name", "email", "whatsapp", "whatsappMessage", "facebook", "bookingUrl", "formEndpoint")}
    (ROOT / "assets" / "js" / "config.js").write_text(
        "/* Generated by tools/build.py from src/site.json. Edit src/site.json, not this file. */\n"
        f"window.SPYD = {json.dumps(config, indent=2)};\n")
    sitemap = "".join(f"  <url><loc>{u}</loc></url>\n" for u in urls)
    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n{sitemap}</urlset>\n')
    (ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {site['siteUrl']}sitemap.xml\n")


if __name__ == "__main__":
    build()
